version: "3"

services:
  appointment-app:
    container_name: appointment-api
    image: appointment-img
    restart: always
    build: 
      .
    ports:
      - 8082:8082 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    depends_on:
      - mysqldb
  
  consultation-app:
    container_name: consultation-api
    image: consultation-img
    restart: always
    build: 
      ../ssa-consultations-api
    ports:
      - 8083:8083 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/sowmya/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: clinicappdb

      

       
   
