version: "3"

services:
  appointment-app:
    container_name: appointment-api
    image: appointment-img
    restart: always
    build: .
    ports:
      - 8082:8082 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_PORT: 3306
      
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/sowmya/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: clinicappdb
      MYSQL_ROOT_PASSWORD: mysql
      

       
   
